--------------------------------------------------------
--  File created - Friday-November-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REMARK_EMP_REG_INFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REMARK_EMP_REG_INFO" 
   (	"EMP_ID" VARCHAR2(20 BYTE), 
	"EMP_MAIL" VARCHAR2(100 BYTE), 
	"EMP_NAME" VARCHAR2(50 BYTE), 
	"EMP_DOB" VARCHAR2(20 BYTE), 
	"EMP_CLGNAME" VARCHAR2(100 BYTE), 
	"EMP_DEPT" VARCHAR2(50 BYTE), 
	"EMP_DEGN" VARCHAR2(30 BYTE), 
	"EMP_FACE_IMG1" CLOB, 
	"EMP_FACE_IMG2" CLOB, 
	"EMP_FACE_IMG3" CLOB, 
	"EMP_FACE_IMG4" CLOB, 
	"EMP_FACE_IMG5" CLOB, 
	"CREATE_TS" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("EMP_FACE_IMG1") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMP_FACE_IMG2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMP_FACE_IMG3") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMP_FACE_IMG4") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMP_FACE_IMG5") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.REMARK_EMP_REG_INFO
SET DEFINE OFF;
Insert into SYSTEM.REMARK_EMP_REG_INFO (EMP_ID,EMP_MAIL,EMP_NAME,EMP_DOB,EMP_CLGNAME,EMP_DEPT,EMP_DEGN,CREATE_TS) values ('1513612','sagarjit.das@tcs.com','Sagarjit Das','02/06/1993','Thapar University','Computer Science and Engineering','Assistant Professor',to_timestamp('27-09-18 11:56:43.000000000 PM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into SYSTEM.REMARK_EMP_REG_INFO (EMP_ID,EMP_MAIL,EMP_NAME,EMP_DOB,EMP_CLGNAME,EMP_DEPT,EMP_DEGN,CREATE_TS) values ('1513605','ramana.kotlin@tcs.com','Ramana Kotlin','02/06/1993','California University','Computer Science and Engineering','Assistant Professor',to_timestamp('28-09-18 11:33:08.000000000 PM','DD-MM-RR HH12:MI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C007076
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007076" ON "SYSTEM"."REMARK_EMP_REG_INFO" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REMARK_EMP_REG_INFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REMARK_EMP_REG_INFO" ADD PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."REMARK_EMP_REG_INFO" MODIFY ("EMP_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REMARK_EMP_REG_INFO" MODIFY ("EMP_ID" NOT NULL ENABLE);
